language: c
script: LC_ALL=en_US.UTF-8 ./make-all && LC_ALL=en_US.UTF-8 make test
sudo: false
dist: xenial
addons:
  apt:
    packages:
    - libpopt-dev
    - libfreetype6-dev
    - language-pack-en
    - build-essential
    - autoconf
    - automake
    - libtool
