#!/bin/sh
#
# This file is distributed under the terms of the MIT License.
# See the LICENSE file at the top of this tree, or if it is missing a copy can
# be found at http://opensource.org/licenses/MIT
#
# Make everything

dir=$(dirname $0)
cd "${dir}"

# Hack for travis-ci
if [ "$1" = "travis-ci" ]; then
	# Travis for the longest time refused to move off the
	# defunct Ubuntu 16.04 (Trusty). Sadly libfreetype6 in
	# 16.04 has a bug that causes rendering errors at the low-
	# resolution our project uses. So, if we're on Travis and
	# the distribution appears to be Ubuntu 16.04, go fetch
	# a newer libfreetype and wire it in.

	. /etc/lsb-release
	# DISTRIB_ID=Ubuntu
	# DISTRIB_RELEASE=14.04

	#if [ "${DISTRIB_ID}" = Ubuntu -a "${DISTRIB_RELEASE}" = 14.04 ]; then
	if true; then (
		rm -rf extra
		mkdir extra
		cd extra
		wget 'http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6-dev_2.6.1-0.1ubuntu2.3_amd64.deb'
		wget 'http://security.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.6.1-0.1ubuntu2.3_amd64.deb'
		dpkg -x libfreetype6-dev_2.6.1-0.1ubuntu2.3_amd64.deb .
		dpkg -x libfreetype6_2.6.1-0.1ubuntu2.3_amd64.deb .
		rm -f *.deb
	) fi

fi

MAKE=make
which gmake >/dev/null 2>&1 && MAKE=gmake
export MAKE
export LD_LIBRARY_PATH=
MAKE_PARALLEL=-j4

do_bootstrap=

if [ -f configure ]; then
	# Find if any autotools input is newer than configure
	if find . -type f '(' -name 'Makefile.*' -or -name 'configure.*' -or -name '*.in' ')' -newer configure | grep -q "."; then
		echo "- autotools out of date; bootstrap required"
		do_bootstrap=y
	fi

	# Find if any autotools output file is missing
	outputs=$(eval $(grep ^ac_config_files= configure); echo $ac_config_files)
	for i in ${outputs}; do
		if [ ! -f "$i" ]; then
			echo "- '$i' is missing; bootstrap required"
			do_bootstrap=y
		fi
	done
else
	echo "- 'configure' is missing; bootstrap required"
	do_bootstrap=y
fi

if [ "${do_bootstrap}" ]; then
	[ -f Makefile ] && $MAKE $MAKE_PARALLEL clean
	./bootstrap
	./do-configure-debug
	$MAKE $MAKE_PARALLEL clean
fi

exec $MAKE $MAKE_PARALLEL
