version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    environment:
      - LC_CTYPE: C
      - LC_ALL: en_US.UTF-8
      - LANG: en_US
      - IS_CI: circleci
    steps:
      - run:
          name: Package dependencies
          command: apt-get update && apt-get install -y build-essential autoconf automake libtool locales libpopt-dev libfreetype6-dev
      - run:
          name: Setup locale
          command: locale-gen $LC_ALL
      - checkout
      - run:
          name: Build
          command: ./make-all
      - run:
          name: Test
          command: make test
