version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    environment:
      - LANG: en_US.UTF-8
      - GDM_LANG: en_US
      - LANGUAGE: en_US
    steps:
      - run:
          name: Package dependencies
          command: apt-get update && apt-get install -y build-essential autoconf automake libtool libpopt-dev libfreetype6-dev
      - checkout
      - run:
          name: Build
          command: ./make-all
      - run:
          name: Test
          command: make test
